name:        mcjoin
version:     0.1.0.0
synopsis:    Telegram bot that notifies when player joins Minecraft server
description: A simple Telegram bot that sends a message when a player joins a
             Minecraft server
category:    Game
github:      chuahou/mcjoin
maintainer:  Chua Hou <human+github@chuahou.dev>

ghc-options:
    - -Wall
    - -fwarn-incomplete-uni-patterns
    - -fwarn-incomplete-record-updates

default-extensions:
    - BangPatterns
    - DeriveGeneric
    - LambdaCase
    - QuasiQuotes
    - TupleSections

dependencies:
    - base          >= 4.13 && < 5
    - attoparsec   ^>= 0.13.2.4
    - cereal       ^>= 0.5.8.1
    - bytestring   ^>= 0.10.10.1
    - network      ^>= 3.1.1.1
    - http-conduit ^>= 2.3.7.3
    - interpolate  ^>= 0.2.1

library:
    source-dirs: src

executable:
    main:         Main.hs
    source-dirs:  exe
    dependencies: mcjoin

extra-doc-files:
    - README.rst
    - CHANGELOG.md
